FROM mcr.microsoft.com/dotnet/sdk:5.0

ENV DOTNET_URLS=http://+:5000

# gdi
RUN apt-get update
RUN apt-get install -y rsync libgif-dev autoconf libtool automake build-essential gettext libglib2.0-dev libcairo2-dev libtiff-dev libexif-dev libgdiplus curl dpkg ca-certificates cabextract debconf wget xfonts-utils fonts-liberation
RUN ln -s /usr/lib/libgdiplus.so /usr/lib/gdiplus.dll

# tools
RUN apt-get install -y jq

# ms fonts
COPY ttf-mscorefonts-installer_3.8_all.deb /var/cache/apt/archives/ttf-mscorefonts-installer_3.8_all.deb
RUN dpkg -i /var/cache/apt/archives/ttf-mscorefonts-installer_3.8_all.deb

# ef
RUN dotnet tool install --global dotnet-ef --version 5.0.10
RUN dotnet dev-certs https

# clean
RUN apt-get clean --dry-run

ENV PATH="$PATH:/root/.dotnet/tools"
