version: "3"
name: uhost-v3
services:
  pgsql:
    extends:
      file: support.yml
      service: pgsql

  redis:
    extends:
      file: support.yml
      service: redis

  adminer:
    extends:
      file: support.yml
      service: adminer

  redis-commander:
    extends:
      file: support.yml
      service: redis-commander

  mailhog:
    extends:
      file: support.yml
      service: mailhog

  mongodb:
    extends:
      file: support.yml
      service: mongodb

  elasticsearch:
    extends:
      file: support.yml
      service: elasticsearch

  graylog:
    extends:
      file: support.yml
      service: graylog

  memcached:
    extends:
      file: support.yml
      service: memcached

  sentry-migrations:
    extends:
      file: support.yml
      service: sentry-migrations

  sentry-cron:
    extends:
      file: support.yml
      service: sentry-cron

  sentry-worker:
    extends:
      file: support.yml
      service: sentry-worker

  sentry-web:
    extends:
      file: support.yml
      service: sentry-web

  # app builder
  builder:
    image: ucezz/dotnet-sdk-gdi:5.0
    container_name: "${APP_NAME}-builder"
    volumes:
      - ../:/src:ro
      - ../storage:/storage
      - app_volume:/app
    depends_on:
      pgsql:
        condition: service_healthy
      redis:
        condition: service_healthy
      graylog:
        condition: service_started
    command: >
      bash -c "
      rm -rf /app/back;
      mkdir -p /app/back/src;
      rsync -vhra /src/ /app/back/src/ --include='**.gitignore' --exclude='/.git' --exclude='/Frontend' --exclude='/Docker' --exclude='/.vscode' --exclude='*.template' --filter=':- .gitignore' --delete-after;
      cp -pf /src/Uhost.Core/appsettings.docker.json /app/back/src/Uhost.Core/appsettings.json || exit 1;
      cp -pf /src/Uhost.Console/default-data.json /app/back/src/Uhost.Console/default-data.json || exit 1;
      cd /app/back/src;
      dotnet ef database update --project Uhost.Core --context PostgreSqlDbContext;
      dotnet ef database update --project Uhost.Core --context PostgreSqlLogDbContext;
      dotnet publish -r linux-x64 -p:PublishSingleFile=true --self-contained true -p:UseAppHost=true -c Release -o /app/back;
      rm -rf /app/back/src;
      /app/back/Uhost.Console loaddefaultdata --file /app/back/default-data.json;
      /app/back/Uhost.Console dbvacuum;"
    logging:
      driver: gelf
      options:
        gelf-address: udp://${FORWARD_HOST}:12201
        tag: builder

  # app runner
  app:
    image: ucezz/dotnet-aspnet-gdi:5.0
    container_name: "${APP_NAME}-app"
    environment:
      ASPNETCORE_ENVIRONMENT: "${ASPNETCORE_ENVIRONMENT}"
    ports:
      - "${FORWARD_HOST}:${FORWARD_HTTP_PORT}:5000"
    volumes:
      - "../storage:/storage"
      - app_volume:/app
    working_dir: /app/back
    restart: unless-stopped
    depends_on:
      pgsql:
        condition: service_healthy
      redis:
        condition: service_healthy
      graylog:
        condition: service_started
      builder:
        condition: service_completed_successfully
    entrypoint: ./Uhost.Web
    logging:
      driver: gelf
      options:
        gelf-address: udp://${FORWARD_HOST}:12201
        tag: api

  # frontend builder
  node:
    image: ucezz/node-rsync:16.17-alpine
    container_name: "${APP_NAME}-node"
    volumes:
      - ../Frontend:/src:ro
      - app_volume:/app
    environment:
      PUBLIC_URL: "${REACT_PUBLIC_URL}"
    command: >
      bash -c "
      rm -rf /app/front;
      mkdir -p /app/front/src;
      rsync -vhra /src/ /app/front/src/ --exclude='node_modules' --exclude='build' --exclude='*.template';

      cd /app/front/src;

      npm i;
      npm run build;

      rsync -vhrat /app/front/src/build/ /app/front/;
      rm -rf /app/front/src;
      ls -lag /app/front;"
    depends_on:
      - graylog
    logging:
      driver: gelf
      options:
        gelf-address: udp://${FORWARD_HOST}:12201
        tag: node

  # full-stack app
  nginx:
    image: nginx:1.25.2-alpine-slim
    container_name: "${APP_NAME}-nginx"
    restart: unless-stopped
    volumes:
      - "app_volume:/app"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      node:
        condition: service_completed_successfully
    ports:
      - "${FORWARD_HOST}:${FORWARD_NGINX_PORT}:80"
    logging:
      driver: gelf
      options:
        gelf-address: udp://${FORWARD_HOST}:12201
        tag: nginx

volumes:
  app_volume:
  postgres_volume:
  graylog_volume:
  mongo_db_volume:
  mongo_cfg_volume:
  redis_volume:
  elasticsearch_volume:
  sentry_volume:
