version: "3"
name: uhost-v3
services:
  pgsql:
    extends:
      file: support.yml
      service: pgsql

  redis:
    extends:
      file: support.yml
      service: redis

  adminer:
    extends:
      file: support.yml
      service: adminer

  redis-commander:
    extends:
      file: support.yml
      service: redis-commander

  mailhog:
    extends:
      file: support.yml
      service: mailhog

  # app builder
  backend-deploy:
    image: ucezz/dotnet-sdk:5.0-gdi
    container_name: "${APP_NAME}-backend-deploy"
    volumes:
      - ../:/src:ro
      - "${EXTERNAL_DIR}/storage:/storage"
      - "${EXTERNAL_DIR}/deploy-win:/deploy/win"
      - deploy_volume:/deploy
      - build_volume:/build
      - build_volume:/root/.nuget
    depends_on:
      pgsql:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      bash -c "
      rm -rf /build/back;
      mkdir -p /build/back;
      rsync -vhra /src/ /build/back/ --include='**.gitignore' --exclude='/.git' --exclude='/Frontend' --exclude='/Docker' --exclude='/.vscode' --exclude='*.template' --filter=':- .gitignore' --delete-after;
      cp -pf /src/Uhost.Core/appsettings.docker.json /build/back/Uhost.Core/appsettings.json || exit 1;
      cp -pf /src/Uhost.Console/default-data.json /build/back/Uhost.Console/default-data.json || exit 1;
      cd /build/back;

      dotnet restore || exit 1;

      dotnet ef database update --project Uhost.Core --context PostgreSqlDbContext || exit 1;
      dotnet ef database update --project Uhost.Core --context PostgreSqlLogDbContext || exit 1;

      rm -rf /deploy/back || exit 1;
      dotnet publish -r linux-x64 --self-contained true -c Release -o /deploy/back || exit 1;

      rm -rf /deploy/win/* || exit 1;
      dotnet publish -r win-x64 -p:PublishSingleFile=true --self-contained true -c Release -o /deploy/win Uhost.Console || exit 1;
      cp -pf /src/Uhost.Core/appsettings.json /deploy/win/appsettings.json || exit 1;

      /deploy/back/Uhost.Console loaddefaultdata --file /deploy/back/default-data.json || exit 1;
      /deploy/back/Uhost.Console updateseq || exit 1;
      /deploy/back/Uhost.Console dbvacuum || exit 1;"

  # app runner
  backend:
    image: ucezz/dotnet-aspnet:5.0-gdi-ffmpeg
    container_name: "${APP_NAME}-backend"
    environment:
      ASPNETCORE_ENVIRONMENT: "${ASPNETCORE_ENVIRONMENT}"
    ports:
      - "${FORWARD_HOST}:${FORWARD_HTTP_PORT}:5000"
    volumes:
      - "${EXTERNAL_DIR}/storage:/storage"
      - deploy_volume:/deploy
    working_dir: /deploy/back
    restart: unless-stopped
    depends_on:
      pgsql:
        condition: service_healthy
      redis:
        condition: service_healthy
      graylog:
        condition: service_started
      backend-deploy:
        condition: service_completed_successfully
    entrypoint: ./Uhost.Web

  # frontend builder
  frontend-deploy:
    image: ucezz/node:16.17-rsync-alpine
    container_name: "${APP_NAME}-frontend-deploy"
    volumes:
      - ../Frontend:/src:ro
      - build_volume:/build
      - deploy_volume:/deploy
    command: >
      bash -c "
      mkdir -p /build/tmp;
      mkdir -p /build/front;
      if [ -d /build/front/node_modules ]; then
        mv -f /build/front/node_modules /build/tmp/node_modules;
      fi;
      rm -rf /build/front/*;
      if [ -d /build/tmp/node_modules ]; then
        mv -f /build/tmp/node_modules /build/front/node_modules;
      fi;

      rsync -vhra /src/ /build/front/ --exclude='node_modules' --exclude='build' --exclude='*.template' --delete;

      cd /build/front;

      npm i;
      npm run build;

      rm -rf /deploy/front;
      mkdir -p /deploy/front;
      rsync -vhrat /build/front/build/ /deploy/front/;
      ls -lag /deploy/front;"

  # frontend and media server
  frontend:
    image: ucezz/nginx:1.16.1-alpine-3.12-vod-lua
    container_name: "${APP_NAME}-frontend"
    restart: unless-stopped
    volumes:
      - deploy_volume:/deploy
      - ${EXTERNAL_DIR}:/opt/static/:ro
      - ./nginx/nginx.conf:/usr/local/nginx/conf/nginx.conf:ro
      - ./nginx/lua:/opt/lua:ro
      - ./nginx/entrypoint.sh:/entrypoint.sh:ro
    depends_on:
      backend-deploy:
        condition: service_completed_successfully
      frontend-deploy:
        condition: service_completed_successfully
    ports:
      - "${FORWARD_HOST}:${FORWARD_NGINX_PORT}:80"

volumes:
  build_volume:
  deploy_volume:
  postgres_volume:
  redis_volume:
