version: "3"
name: uhost-v3
services:
  pgsql:
    extends:
      file: app.yml
      service: pgsql

  redis:
    extends:
      file: app.yml
      service: redis

  adminer:
    extends:
      file: app.yml
      service: adminer

  redis-commander:
    extends:
      file: app.yml
      service: redis-commander

  mailhog:
    extends:
      file: app.yml
      service: mailhog

  builder:
    extends:
      file: app.yml
      service: builder

  mongodb:
    extends:
      file: support.yml
      service: mongodb

  elasticsearch:
    extends:
      file: support.yml
      service: elasticsearch

  graylog:
    extends:
      file: support.yml
      service: graylog

  app:
    extends:
      file: app.yml
      service: app

  prometheus:
    image: prom/prometheus:v2.30.3
    container_name: "${APP_NAME}-prometheus"
    restart: unless-stopped
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
    ports:
      - "${FORWARD_HOST}:${FORWARD_PROMETHEUS_PORT}:9090"

  postgres-exporter:
    container_name: "${APP_NAME}-postgres-exporter"
    image: wrouesnel/postgres_exporter:latest
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DATA_SOURCE_NAME: "postgresql://${PGSQL_USERNAME}:${PGSQL_PASSWORD}@pgsql:5432/${PGSQL_DATABASE}?sslmode=disable"
    ports:
      - 9187:9187

  grafana:
    image: grafana/grafana:9.2.10
    container_name: "${APP_NAME}-grafana"
    depends_on:
      - pgsql
    ports:
      - "${FORWARD_HOST}:${FORWARD_GRAFANA_PORT}:3000"

  zabbix-server:
    container_name: "${APP_NAME}-zabbix-server"
    image: zabbix/zabbix-server-pgsql
    environment:
      TZ: "Europe/Moscow"
      DB_SERVER_HOST: pgsql
      DB_SERVER_PORT: 5432
      DB_SERVER_SCHEMA: "${PGSQL_SCHEMA}"
      POSTGRES_USER: "${PGSQL_USERNAME}"
      POSTGRES_PASSWORD: "${PGSQL_PASSWORD}"
      POSTGRES_DB: "${PGSQL_DATABASE}"
      #ZBX_JAVAGATEWAY : zabbix-java
    depends_on:
      - pgsql

  zabbix-web:
    container_name: "${APP_NAME}-zabbix-web"
    image: zabbix/zabbix-web-apache-pgsql
    environment:
      TZ: "Europe/Moscow"
      DB_SERVER_HOST: pgsql
      DB_SERVER_PORT: 5432
      DB_SERVER_SCHEMA: "${PGSQL_SCHEMA}"
      POSTGRES_USER: "${PGSQL_USERNAME}"
      POSTGRES_PASSWORD: "${PGSQL_PASSWORD}"
      POSTGRES_DB: "${PGSQL_DATABASE}"
      ZBX_HOSTNAME: zabbix-server
      ZBX_SERVER_HOST: zabbix-server
    ports:
      - "${FORWARD_HOST}:${FORWARD_ZABBIX_PORT}:8080"
    depends_on:
      - pgsql
      - zabbix-server

  zabbix-agent:
    container_name: "${APP_NAME}-zabbix-agent"
    image: zabbix/zabbix-agent2
    privileged: true
    environment:
      TZ: "Europe/Moscow"
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: pgsql
      DB_SERVER_PORT: 5432
      DB_SERVER_SCHEMA: "${PGSQL_SCHEMA}"
      POSTGRES_USER: "${PGSQL_USERNAME}"
      POSTGRES_PASSWORD: "${PGSQL_PASSWORD}"
      POSTGRES_DB: "${PGSQL_DATABASE}"
      ZBX_HOSTNAME: zabbix-server
    links:
      - "zabbix-server:zabbix-server"
    depends_on:
      - zabbix-server
      - pgsql

volumes:
  app_volume:
  postgres_volume:
  graylog_volume:
  mongo_volume:
  redis_volume:
  elasticsearch_volume:
