version: "3"
name: uhost-v3
services:
  pgsql:
    extends:
      file: app.yml
      service: pgsql

  redis:
    extends:
      file: app.yml
      service: redis

  adminer:
    extends:
      file: app.yml
      service: adminer

  redis-commander:
    extends:
      file: app.yml
      service: redis-commander

  mailhog:
    extends:
      file: app.yml
      service: mailhog

  builder:
    extends:
      file: app.yml
      service: builder

  app:
    extends:
      file: app.yml
      service: app

  mongodb:
    extends:
      file: app.yml
      service: mongodb

  elasticsearch:
    extends:
      file: app.yml
      service: elasticsearch

  graylog:
    extends:
      file: app.yml
      service: graylog

  memcached:
    extends:
      file: app.yml
      service: memcached

  sentry-migrations:
    extends:
      file: app.yml
      service: sentry-migrations

  sentry-cron:
    extends:
      file: app.yml
      service: sentry-cron

  sentry-worker:
    extends:
      file: app.yml
      service: sentry-worker

  sentry-web:
    extends:
      file: app.yml
      service: sentry-web

  postgres-exporter:
    container_name: "${APP_NAME}-postgres-exporter"
    image: wrouesnel/postgres_exporter:latest
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DATA_SOURCE_NAME: "postgresql://${PGSQL_USERNAME}:${PGSQL_PASSWORD}@pgsql:5432/${PGSQL_DATABASE}?sslmode=disable"
    ports:
      - 9187:9187

  prometheus:
    image: prom/prometheus:v2.30.3
    container_name: "${APP_NAME}-prometheus"
    restart: unless-stopped
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
    ports:
      - "${FORWARD_HOST}:${FORWARD_PROMETHEUS_PORT}:9090"

  grafana:
    image: grafana/grafana:9.2.10
    container_name: "${APP_NAME}-grafana"
    depends_on:
      - pgsql
      - postgres-exporter
    links:
      - pgsql
      - postgres-exporter
    ports:
      - 3000:3000
      - "${FORWARD_HOST}:${FORWARD_GRAFANA_PORT}:3000"

volumes:
  app_volume:
  postgres_volume:
  graylog_volume:
  mongo_db_volume:
  mongo_cfg_volume:
  redis_volume:
  elasticsearch_volume:
  sentry_volume:
