version: "3"
name: uhost-v3
services:
  pgsql:
    extends:
      file: app.yml
      service: pgsql

  redis:
    extends:
      file: app.yml
      service: redis

  adminer:
    extends:
      file: app.yml
      service: adminer

  redis-commander:
    extends:
      file: app.yml
      service: redis-commander

  mailhog:
    extends:
      file: app.yml
      service: mailhog

  builder:
    extends:
      file: app.yml
      service: builder

  app:
    extends:
      file: app.yml
      service: app

  prometheus:
    image: prom/prometheus:v2.30.3
    container_name: "${APP_NAME}-prometheus"
    restart: unless-stopped
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
    ports:
      - "${FORWARD_HOST}:${FORWARD_PROMETHEUS_PORT}:9090"

  grafana:
    image: grafana/grafana:9.2.10
    container_name: "${APP_NAME}-grafana"
    depends_on:
      - pgsql
    ports:
      - "${FORWARD_HOST}:${FORWARD_GRAFANA_PORT}:3000"

  zabbix-server:
    container_name: "${APP_NAME}-zabbix-server"
    image: zabbix/zabbix-server-pgsql
    environment:
      TZ: "Europe/Moscow"
      DB_SERVER_HOST: pgsql
      DB_SERVER_PORT: 5432
      DB_SERVER_SCHEMA: "${PGSQL_SCHEMA}"
      POSTGRES_USER: "${PGSQL_USERNAME}"
      POSTGRES_PASSWORD: "${PGSQL_PASSWORD}"
      POSTGRES_DB: "${PGSQL_DATABASE}"
      #ZBX_JAVAGATEWAY : zabbix-java
    depends_on:
      - pgsql

  zabbix-web:
    container_name: "${APP_NAME}-zabbix-web"
    image: zabbix/zabbix-web-apache-pgsql
    environment:
      TZ: "Europe/Moscow"
      DB_SERVER_HOST: pgsql
      DB_SERVER_PORT: 5432
      DB_SERVER_SCHEMA: "${PGSQL_SCHEMA}"
      POSTGRES_USER: "${PGSQL_USERNAME}"
      POSTGRES_PASSWORD: "${PGSQL_PASSWORD}"
      POSTGRES_DB: "${PGSQL_DATABASE}"
      ZBX_HOSTNAME: zabbix-server
      ZBX_SERVER_HOST: zabbix-server
    ports:
      - "${FORWARD_HOST}:${FORWARD_ZABBIX_PORT}:8080"
    depends_on:
      - pgsql
      - zabbix-server

  zabbix-agent:
    container_name: "${APP_NAME}-zabbix-agent"
    image: zabbix/zabbix-agent2
    privileged: true
    environment:
      TZ: "Europe/Moscow"
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: pgsql
      DB_SERVER_PORT: 5432
      DB_SERVER_SCHEMA: "${PGSQL_SCHEMA}"
      POSTGRES_USER: "${PGSQL_USERNAME}"
      POSTGRES_PASSWORD: "${PGSQL_PASSWORD}"
      POSTGRES_DB: "${PGSQL_DATABASE}"
      ZBX_HOSTNAME: zabbix-server
    links:
      - "zabbix-server:zabbix-server"
    depends_on:
      - zabbix-server
      - pgsql

  mongodb:
    container_name: "${APP_NAME}-mongo"
    image: mongo:3

  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docker.html
  elasticsearch:
    container_name: "${APP_NAME}-elasticsearch"
    image: elasticsearch:5.6.3
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      # Disable X-Pack security: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/security-settings.html#general-security-settings
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g

  graylog:
    container_name: "${APP_NAME}-graylog"
    image: graylog/graylog:2.4.0-1
    environment:
      # CHANGE ME!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_WEB_ENDPOINT_URI=http://127.0.0.1:9000/api
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - "${FORWARD_HOST}:${FORWARD_GRAYLOG_PORT}:9000"
      - "5044:5044/tcp" # Beats
      - "5140:5140/udp" # Syslog
      - "5140:5140/tcp" # Syslog
      - "5555:5555/tcp" # RAW TCP
      - "5555:5555/udp" # RAW TCP
      - "12201:12201/tcp" # GELF TCP
      - "12201:12201/udp" # GELF UDP
      - "13301:13301/tcp" # Forwarder data
      - "13302:13302/tcp" # Forwarder config
    volumes:
      - "graylog_data_volume:/usr/share/graylog/data/data"
      - "graylog_journal_volume:/usr/share/graylog/data/journal"

volumes:
  app_volume:
  db_volume:
  graylog_data_volume:
  graylog_journal_volume:
