global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
      - targets: ["prometheus:9090"]

remote_write:
  - url: "grafana:3000"
    basic_auth:
      username: "admin"
      password: "admin"
