version: "3"
name: uhost-v3
services:
  # PostgreSql
  pgsql:
    image: postgres:14-alpine
    container_name: "${APP_NAME}-pgsql"
    restart: unless-stopped
    environment:
      PGPASSWORD: "${PGSQL_PASSWORD}"
      POSTGRES_DB: "${PGSQL_DATABASE}"
      POSTGRES_DB_LOGS: "${PGSQL_DATABASE_LOGS}"
      POSTGRES_USER: "${PGSQL_USERNAME}"
      POSTGRES_PASSWORD: "${PGSQL_PASSWORD}"
      POSTGRES_DB_SCHEMA: "${PGSQL_SCHEMA}"
    ports:
      - "${FORWARD_HOST}:${FORWARD_PGSQL_PORT:-5432}:5432"
    volumes:
      - "./pginit.sh:/docker-entrypoint-initdb.d/init.sh"
      - postgres_volume:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "${PGSQL_DATABASE}",
          "-U",
          "${PGSQL_USERNAME}",
        ]
      retries: 3
      timeout: 10s

  # Redis
  redis:
    image: redis:6.0-alpine
    container_name: "${APP_NAME}-redis"
    restart: unless-stopped
    ports:
      - "${FORWARD_HOST}:${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - redis_volume:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 10s

  # Postgres Web UI
  adminer:
    image: adminer
    container_name: "${APP_NAME}-adminer"
    ports:
      - "${FORWARD_HOST}:${FORWARD_ADMINER_PORT:-8081}:8080"
    depends_on:
      - pgsql
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_SERVER: pgsql
      ADMINER_DESIGN: hever
      ADMINER_DEFAULT_DB_NAME: "${PGSQL_DATABASE}"

  # Redis Web UI
  redis-commander:
    container_name: "${APP_NAME}-redis-cmdr"
    image: rediscommander/redis-commander:latest
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=local:redis:6379:${REDIS_DB_NUM}
    ports:
      - "${FORWARD_HOST}:${FORWARD_REDIS_CMDR_PORT:-8082}:8081"

  # Mailhog
  mailhog:
    image: mailhog/mailhog:latest
    container_name: "${APP_NAME}-mailhog"
    restart: unless-stopped
    ports:
      - "${FORWARD_HOST}:${FORWARD_MAILHOG_PORT:-8025}:1025"
      - "${FORWARD_HOST}:${FORWARD_MAILHOG_DASHBOARD_PORT:-8083}:8025"

  # nginx dev
  nginx-dev:
    container_name: "${APP_NAME}-nginx-dev"
    image: ucezz/nginx:1.25.5-alpine-3.18-vod-lua
    environment:
      REDIS_DBNUM: ${REDIS_DB_NUM}
      VIDEO_TOKEN_SALT: ${VIDEO_TOKEN_SALT}
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - ${EXTERNAL_DIR}/videos:/opt/static/videos:ro
      - ./nginx/nginx-dev.conf:/usr/local/nginx/conf/nginx.conf:ro
      - ./nginx/lua:/opt/lua:ro
      - ./nginx/entrypoint.sh:/entrypoint.sh:ro
      - ../Uhost.Web/wwwroot:/opt/static/wwwroot:ro
    ports:
      - "${FORWARD_HOST}:${FORWARD_NGINX_DEV_PORT:-8180}:80"
    entrypoint: /entrypoint.sh

volumes:
  postgres_volume:
  redis_volume:
