//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uhost.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogEvents {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogEvents() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Uhost.Core.Properties.LogEvents", typeof(LogEvents).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комментарий удалён.
        /// </summary>
        internal static string CommentDeleted {
            get {
                return ResourceManager.GetString("CommentDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комментарий добавлен.
        /// </summary>
        internal static string CommentPosted {
            get {
                return ResourceManager.GetString("CommentPosted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка выполнения консольной команды.
        /// </summary>
        internal static string ConsoleCommandError {
            get {
                return ResourceManager.GetString("ConsoleCommandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка данных по умолчанию.
        /// </summary>
        internal static string ConsoleLoadDefaultData {
            get {
                return ResourceManager.GetString("ConsoleLoadDefaultData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка отправки Email.
        /// </summary>
        internal static string EmailSendError {
            get {
                return ResourceManager.GetString("EmailSendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл удалён.
        /// </summary>
        internal static string FileDeleted {
            get {
                return ResourceManager.GetString("FileDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл удалён с диска.
        /// </summary>
        internal static string FileDeletedPhysically {
            get {
                return ResourceManager.GetString("FileDeletedPhysically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка размещения файла.
        /// </summary>
        internal static string FileStoreFail {
            get {
                return ResourceManager.GetString("FileStoreFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл загружен.
        /// </summary>
        internal static string FileUploaded {
            get {
                return ResourceManager.GetString("FileUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка загрузки файла.
        /// </summary>
        internal static string FileUploadFail {
            get {
                return ResourceManager.GetString("FileUploadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сессия пользователя завершена.
        /// </summary>
        internal static string SessionTerminated {
            get {
                return ResourceManager.GetString("SessionTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвестный тип события.
        /// </summary>
        internal static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход пользователя.
        /// </summary>
        internal static string UserAuth {
            get {
                return ResourceManager.GetString("UserAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неудачная попытка входа.
        /// </summary>
        internal static string UserAuthFail {
            get {
                return ResourceManager.GetString("UserAuthFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка аватара.
        /// </summary>
        internal static string UserAvatarUploaded {
            get {
                return ResourceManager.GetString("UserAvatarUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь заблокирован.
        /// </summary>
        internal static string UserBanned {
            get {
                return ResourceManager.GetString("UserBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход пользователя.
        /// </summary>
        internal static string UserLogOut {
            get {
                return ResourceManager.GetString("UserLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь зарегистрирован.
        /// </summary>
        internal static string UserRegistered {
            get {
                return ResourceManager.GetString("UserRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрос регистрации.
        /// </summary>
        internal static string UserRegisterQuery {
            get {
                return ResourceManager.GetString("UserRegisterQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конвертация видео завершена.
        /// </summary>
        internal static string VideoConversionCompleted {
            get {
                return ResourceManager.GetString("VideoConversionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конвертация видео не удалась.
        /// </summary>
        internal static string VideoConversionFailed {
            get {
                return ResourceManager.GetString("VideoConversionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Видео удалено.
        /// </summary>
        internal static string VideoDeleted {
            get {
                return ResourceManager.GetString("VideoDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Видео изменено.
        /// </summary>
        internal static string VideoEdited {
            get {
                return ResourceManager.GetString("VideoEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получено видео со стороннего сервера.
        /// </summary>
        internal static string VideoFetchCompleted {
            get {
                return ResourceManager.GetString("VideoFetchCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось получить видео со стороннего сервера.
        /// </summary>
        internal static string VideoFetchFailed {
            get {
                return ResourceManager.GetString("VideoFetchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Видео загружено.
        /// </summary>
        internal static string VideoUploaded {
            get {
                return ResourceManager.GetString("VideoUploaded", resourceCulture);
            }
        }
    }
}
