//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uhost.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApiStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiStrings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Uhost.Web.Properties.ApiStrings", typeof(ApiStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь {0} заблокирован {1} пользователем {2} по причине &quot;{3}&quot;.
        /// </summary>
        internal static string Auth_Error_BlockFmt {
            get {
                return ResourceManager.GetString("Auth_Error_BlockFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный логин или пароль.
        /// </summary>
        internal static string Auth_Error_InvalidCredentials {
            get {
                return ResourceManager.GetString("Auth_Error_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь не авторизован.
        /// </summary>
        internal static string Auth_Error_Unauthorized {
            get {
                return ResourceManager.GetString("Auth_Error_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комментирование этого видео отключено.
        /// </summary>
        internal static string Comment_Error_NotAllowed {
            get {
                return ResourceManager.GetString("Comment_Error_NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Коммментарий не найден.
        /// </summary>
        internal static string Comment_Error_NotFound {
            get {
                return ResourceManager.GetString("Comment_Error_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неопознанная ошибка.
        /// </summary>
        internal static string Common_Error_Common {
            get {
                return ResourceManager.GetString("Common_Error_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректное значение.
        /// </summary>
        internal static string Common_Error_Invalid {
            get {
                return ResourceManager.GetString("Common_Error_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слишком много запросов.
        /// </summary>
        internal static string Common_Error_TooManyRequests {
            get {
                return ResourceManager.GetString("Common_Error_TooManyRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь не авторизован.
        /// </summary>
        internal static string Common_Error_Unauthorized {
            get {
                return ResourceManager.GetString("Common_Error_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл с таким ид. не найден.
        /// </summary>
        internal static string File_Error_NotFoundById {
            get {
                return ResourceManager.GetString("File_Error_NotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимый тип файла, допустимые значения: {0}.
        /// </summary>
        internal static string File_Error_TypeFail {
            get {
                return ResourceManager.GetString("File_Error_TypeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Реакции к этому видео отключены.
        /// </summary>
        internal static string Reaction_Error_NotAllowed {
            get {
                return ResourceManager.GetString("Reaction_Error_NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Письмо с кодом подтверждения успешно отправлено.
        /// </summary>
        internal static string Register_EmailSent {
            get {
                return ResourceManager.GetString("Register_EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недействительный код подтверждения.
        /// </summary>
        internal static string Register_Error_ConfirmFail {
            get {
                return ResourceManager.GetString("Register_Error_ConfirmFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось отправить письмо.
        /// </summary>
        internal static string Register_Error_FailedToSend {
            get {
                return ResourceManager.GetString("Register_Error_FailedToSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Право с ид. {0} не найдено.
        /// </summary>
        internal static string Right_Error_NotFoundByIdFmt {
            get {
                return ResourceManager.GetString("Right_Error_NotFoundByIdFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь должен иметь следующие права: {0}.
        /// </summary>
        internal static string Right_Error_ShouldHaveAll {
            get {
                return ResourceManager.GetString("Right_Error_ShouldHaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь должен иметь хотя бы одно из следующих прав: {0}.
        /// </summary>
        internal static string Right_Error_ShouldHaveAny {
            get {
                return ResourceManager.GetString("Right_Error_ShouldHaveAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Роль с таким именем уже существует.
        /// </summary>
        internal static string Role_Error_AlreadyExists {
            get {
                return ResourceManager.GetString("Role_Error_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Роль с даким ид. не найдена.
        /// </summary>
        internal static string Role_Error_NotFoundById {
            get {
                return ResourceManager.GetString("Role_Error_NotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Роль с ид. {0} не найдена.
        /// </summary>
        internal static string Role_Error_NotFoundByIdFmt {
            get {
                return ResourceManager.GetString("Role_Error_NotFoundByIdFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .opblock-summary-path,.swagger-ui .markdown code,.swagger-ui .parameter__type,.swagger-ui .renderedMarkdown code,code,pre,textarea.body-param__text{font-family:Consolas,&apos;Courier New&apos;,Courier,monospace!important}a{color:#8c8cfa}embed[type=&quot;application/pdf&quot;]{filter:invert(90%)}html{background:#1f1f1f!important;box-sizing:border-box;filter:contrast(100%) brightness(100%) saturate(100%);overflow-y:scroll}body{background:#1f1f1f;background-image:none!important}.swagger-ui input[disabled],.swagger-ui select[disab [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string SwaggerStylesheet {
            get {
                return ResourceManager.GetString("SwaggerStylesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь с таким логином или email уже существует.
        /// </summary>
        internal static string User_Error_AlreadyExists {
            get {
                return ResourceManager.GetString("User_Error_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь с таким ид. не найден.
        /// </summary>
        internal static string User_Error_NotFoundById {
            get {
                return ResourceManager.GetString("User_Error_NotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Видео не найдено.
        /// </summary>
        internal static string Video_Error_NotFound {
            get {
                return ResourceManager.GetString("Video_Error_NotFound", resourceCulture);
            }
        }
    }
}
